### ISSUE TITLE
Stuck on step 2

### ISSUE THREAD

**Issue by GeorgeKanchev** [aido179/react-deploy-sftp#1]
Hey, I thought I'd just ask the question here.

When I run `rup deploy staging`, the process is stuck at step 2, looks like this:

`Deployment :: SFTP connection ready`
`Deployment :: setting up...`

Password/Username are correct, remote folder is correct, the host is also correct, can't figure out what the issue might be, Do you know what might be up?

**Comment by aido179** [comment]
Sorry for the late reply. Just saw the notification now. 

It looks like I have accidentally hardcoded the file owner and user group as:
    owner: "aidan",
    group: "www-data"
Try changing that to the username on the machine. This definitely needs to be fixed.

**Comment by aido179** [comment]
Hi, this is almost 3 years later...sorry. 
Version 2 has been published and it allows setting "remoteDirOwner" and "remoteDirGroup".
Hopefully this will fix your issue.
